LittleCorner::Application.routes.draw do
  root :to           => "home#index"
  match "blog"       => "blog#index"
  match "delicious"  => "delicious#index"
  match "contact"    => "contact#index"
  match "flickr"     => "flickr#index"
  match "foursquare" => "foursquare#index"
  match "foursquare/callback"
  match "foursquare/connect"
  match "github"     => "github#index"
  match "home"       => "home#index"
  match "instagram"  => "instagram#index"
  match "instagram/callback"
  match "instagram/connect"
  match "lastfm"     => "lastfm#index"
  match "projects"   => "projects#index"
  match "soundcloud" => "soundcloud#index"
  match "tumblr"     => "tumblr#index"
  match "twitter"    => "twitter#index"
  match "untappd"    => "untappd#index"
end
